doctor/urls.py
from django.urls import path
from . import views

app_name='doctor'
urlpatterns = [
    path('',views.index, name='index'),
    path('login',views.login, name='login'),
    path('register',views.register, name='register')
   
]

hospitalerp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('doctor/', include('doctor.urls')),
    path('patients/',include('patients.urls')),
    path('nurse/',include('nurse.urls'))
]

nurse/urls.py
from django.urls import path
from .import views
urlpatterns = [
    path('home',views.home)
   
]

patients/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('home',views.home)
   
]

doctor/models.py
from django.db import models

# Create your models here.

nurse/models.py
from django.db import models

# Create your models here.

patients/models.py
from django.db import models

# Create your models here.

doctor/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

# def index(request):
#     return HttpResponse('this is doctor module')

def index(request):
    return render(request, 'doctor_templates/home.html')


def login(request):
    return render(request, 'doctor_templates/login.html')    


def register(request):
    return render(request, 'doctor_templates/register.html')      

nurse/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def home(request):
    return HttpResponse('nurse home screen')

patients/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
def home(request):
    return HttpResponse('patients home screen')

doctor/templates/doctor_templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
   <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro cumque adipisci, quo cupiditate deserunt quaerat ex illo possimus praesentium vitae temporibus magnam autem error. Laudantium corrupti laboriosam earum rem iste?</h1> 
    <img src="{% static 'images/img.jpeg' %}" alt="">
    <p>welcome to home page</p>
    <a href="{% url 'doctors:register' %}"><input type="button" value="go to register"></a>
    <h2>Hello wold</h2>
    <p>welcome to django projects</p>

</body>
</html>

doctor/templates/doctor_templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <input type="text" placeholder="Enter your email"><br>
    <input type="text" placeholder="Enter your password"><br>
    
   <a href="{% url 'doctor:index' %}"> <input type="button" value="sign in"></a>
   <img src="{% static 'images/img2.jpeg' %}" alt="" height="100">
</body>
</html>

doctor/templates/doctor_templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <input type="text" placeholder="Enter your first name"><br>
    <input type="text" placeholder="Enter your second name"><br>
    <input type="text" placeholder="Enter your email id"><br>
    <input type=" password" placeholder="Enter your password"><br>
    <input type="password" placeholder="Re enter your password"><br>
    <input type="button" value="Register">
</body>
</html>